### ISSUE TITLE
Evaluate adding additional icons

### ISSUE THREAD

**Issue by jtlowe** [jtlowe/studio-icons#1]
**From Material Icon Theme:**
- ~adobe illustrator~
- ~adobe indesign~
- ~adobe photoshop~
- docker
- go
- gradle
- gulp
- iconic
- pdf
- ~microsoft access~
- ~microsoft excel~
- ~microsoft powerpoint~
- ~microsoft word~
- ~microsoft visio~
- ~readme~
- ~rust~
- swift
- tex
- tune
- web pack
- yaml
- yarn

**Comment by jtlowe** [comment]
Added icons for adobe illustrator, indesign, photoshop

**Comment by jtlowe** [comment]
Added initial Microsoft Office icons

**Comment by LordZane** [comment]
I would love icons for .rs (Rust), and .toml (TOML)

**Comment by jtlowe** [comment]
No problem. I'll take a shot at the Rust icon soon. I think two options may be to have the Rust logo at the full icon size or spell out RUST for an icon like the SassStylesheet_16x one. I'd like the logo to overlay a document icon, like the ASPXFile_16x, but I think the logo will be unrecognizable at the small size.

Do you have any direction at all on the TOML icon? Is there a logo or any sort of imagery that will identify as TOML?

**Comment by LordZane** [comment]
I think either would look good, bot yeah it would probably be too hard to see the icon.

As for TOML, you could use SettingsFile_16x, as their is no logo for TOML. You could also perhaps overlay the [cargo symbol](https://crates.io/) on a file as TOML is what cargo uses as a config format, and I don't think its that popular for general configs, and most people use JSON or something similar. Then again, I like rust so im biased :)

**Comment by jtlowe** [comment]
Here's what I'm planning to include for the Rust Icon. It keeps the Rust logo's "R" but uses a simpler gear to work better at 16x16. 

![rustfile_16x](https://cloud.githubusercontent.com/assets/766226/21793388/6cd8a0c2-d6b6-11e6-86bd-4b83aa681087.png)
![rustfile_32x](https://cloud.githubusercontent.com/assets/766226/21793389/6cf0a7ee-d6b6-11e6-93d3-ca0a5c4db1f2.png)

**Comment by LordZane** [comment]
Im assuming the bottom one is the default size? If so it looks great acctauly, and I like how its red and stands out unlike other editors which use a black icon. The smaller icon on top is abit too had to see though, maybe make it just the gear part and remove the file? If its not the default size it might not be important anyways and not matter

**Comment by jtlowe** [comment]
The smaller 16x16 icon will be the default. You're right, it's not very visible but I think it will be a little better when rendered as a SVG. It's still not that great though so I'm going to attach soon a couple of other ideas. I'd still like to find a way to incorporate the icon within the document icon to keep consistency with other icons. If nothing works, I'll just fall back to having the logo gear/r as the whole icon. I might have to modify it though cause the official logo still doesn't work well at the 16x16 default size. I hope to have something soon. Thanks a lot for all your help so far!

**Comment by jtlowe** [comment]
Here's a screenshot of the rust icon I came up with. The "R" is hard to work in at 16x16, but hopefully this should be suitable for now. I'll publish the update shortly.

![rust-icon-preview-screenshot](https://cloud.githubusercontent.com/assets/766226/22048747/ae078358-dcf4-11e6-8fde-2e04885ff2c4.png)

**Comment by jtlowe** [comment]
Studio Icons v1.3.0 has been published!

**Comment by LordZane** [comment]
Looks great! thanks so much. For TOML you could use ConfigurationFile_16x.svg, or if vscode supports exact file names, use some kind of package looking icon, like what https://github.com/file-icons/atom does

**Comment by jtlowe** [comment]
I haven't forgot about the TOML icon, just been insanely busy. I'll plan to use the ConfigurationFile_16.svg for now, until I can have time to look into creating a box or crate-like icon.

**Comment by jtlowe** [comment]
Forgot to comment on the progress. Version 1.4.0 was release a few days ago and maps the ConfigurationFile_16.svg icon to the .toml file extension.
