### ISSUE TITLE
csproj missing icon?

### ISSUE THREAD

**Issue by kotakerdus** [jtlowe/studio-icons#11]
On the preview it does have csproj file icon but tried on mine it seems that it is missing?

![image](https://user-images.githubusercontent.com/33751190/43406765-22d67a4e-9447-11e8-84f8-7ede99e8509e.png)

**Comment by christofferjerrebo** [comment]
I believe it's because ".csproj" is listed under "fileNames" in studio-icons.json. It should be listed as "csproj" under "fileExtensions" instead. I changed it locally and it worked for me.

**Comment by jtlowe** [comment]
Sorry I missed this issue. I should have a new version out shortly.

**Comment by jtlowe** [comment]
@christofferjerrebo that was the problem. I've created a new 1.6.3 version. Please let me know of any problems. Thanks!
