### ISSUE TITLE
Request icon for pug files.

### ISSUE THREAD

**Issue by VitorLuizC** [jtlowe/studio-icons#3]
Request icon for pug files.
Jade was renamed to Pug. Pug/Jade is a view-engine, a pré-processor that renders into HTML files.

![Pug logo](http://bit.ly/2aHfYIA)

**Comment by jtlowe** [comment]
Thanks! I'll see what I can do soon as far as adding an icon that fits in with the look of the icon library. Hopefully the VS 2017 icon set will include an icon for pug since they had one for Jade. The only file to associate with this icon is ".pug", right?

**Comment by VitorLuizC** [comment]
> The only file to associate with this icon is ".pug", right?

Yeap, only .pug files

**Comment by jtlowe** [comment]
I've published version 1.5.0 with an icon for .pug file extension. It's basically the JADE file icon but with "PUG" instead. I tried a few different things for the icon but they all didn't come out very well, so I stuck with the JADE inspired icon. Please let me know what you think. Hopefully VS 2017 icon library will include a good one for PUG.
