### ISSUE TITLE
Request for .pdf icon

### ISSUE THREAD

**Issue by jx22** [jtlowe/studio-icons#5]
Hello! I love Studio Icons in my custom dark VSCode theme. I see now that one file type that doesn't have a file icon is .pdf. Is there some way that I could add an existing .pdf icon to the theme, or is there some way for you to add one? Thank you!

**Comment by jtlowe** [comment]
Thanks! I'll see if there's a PDF icon in the library. I originally tried to match how Visual Studio displays the icon (which uses the PDF icon from the windows system). But I agree that the PDF icon would look nice. 

I can try to make one if it's not in the library, but it's hard to do them as well as the Microsoft designers make them. 

I'll try adding the icon soon. 



Thanks
Jordan

On Aug 8, 2017, at 10:12 AM, jx22 <notifications@github.com> wrote:

Hello! I love Studio Icons in my custom dark VSCode theme. I see now that one file type that doesn't have a file icon is .pdf. Is there some way that I could add an existing .pdf icon to the theme, or is there some way for you to add one? Thank you!

**Comment by jx22** [comment]
Sounds good, thanks -- looking forward to seeing what you come up with.

**Comment by jtlowe** [comment]
I've finally had time to make a file icon for this. It follows the same basic look as a lot of other files. I may create a more detailed version soon if I have the time. I'll get this in a new release soon.

![pdffile_16x](https://user-images.githubusercontent.com/766226/32642216-5560cd26-c598-11e7-8101-7d59c6c57820.png)

**Comment by jtlowe** [comment]
This new icons is available in the latest studio icons version 1.6.1.
