### ISSUE TITLE
Request for .asm and Makefile icons

### ISSUE THREAD

**Issue by LordZane** [jtlowe/studio-icons#6]
I'm pretty sure visual studio already has an assembly icon, im not sure about makefiles

**Comment by jtlowe** [comment]
Thanks for the request! I think I've found the right icons from the Image Library. If they look good to you, I'll get them in a new release soon.

![assemblersourcefile_16x](https://user-images.githubusercontent.com/766226/32642265-a6d4908e-c598-11e7-862a-46ed55c16ce6.png)
![makefile_16x](https://user-images.githubusercontent.com/766226/32642283-c46213ce-c598-11e7-924c-f71888cdee6e.png)

**Comment by LordZane** [comment]
Looks great!

**Comment by jtlowe** [comment]
These new icons are available in the latest studio icons version 1.6.1.
