### ISSUE TITLE
Support root folder icons

### ISSUE THREAD

**Issue by bpasero** [jtlowe/studio-icons#7]
VS Code will enable multi-root support for the upcoming October release (early November) and it would be great if studio-icons would support root folder icons. See https://code.visualstudio.com/updates/v1_15#_icon-for-root-folders for more details.

**Comment by jtlowe** [comment]
Thanks for letting me know about this! I hope to have this implemented very soon.

Here are the two icons I've found in the VS Image Library that I think closely match Code's screenshot.

![specialfolderopen_16x](https://user-images.githubusercontent.com/766226/32642145-cb7e02ae-c597-11e7-9ff2-a1eacf3c97c2.png)
![specialfolder_16x](https://user-images.githubusercontent.com/766226/32642146-cb9de65a-c597-11e7-8ffc-5597817a6ad7.png)

**Comment by jtlowe** [comment]
This has been implemented in release 1.6.1
