### ISSUE TITLE
No change after install

### ISSUE THREAD

**Issue by urbanhop** [jtlowe/studio-icons#9]
I installed this theme but nothing changed. So I guess I need a theme that uses these icons, right? How would I do that?

Thank you for your work

**Comment by jtlowe** [comment]
Hi @urbanhop,

I think you still need to activate the icon theme. After installing the extension, you have to go to the preferences menu and select the "File Icon Theme" option. This will bring up the menu to select different icon themes. 

Here are the instructions from the VS Code site: [https://code.visualstudio.com/docs/getstarted/themes#_selecting-the-file-icon-theme](https://code.visualstudio.com/docs/getstarted/themes#_selecting-the-file-icon-theme)

I wish they would make it easier on us and prompt to switch icon themes upon install.

**Comment by urbanhop** [comment]
Thank you very much Jordan, took me just seconds with your help. 

Nice work and thank you for your fast assistance. Beautiful web apps in your portfolio, looks like we share visual preferences, these icons, monospace fonts and flat design ;-)
